name = "maintenance"
main = "worker.js"
compatibility_date = "2024-03-20"

[[d1_databases]]
binding = "DB"
database_name = "equiplocate-db"
database_id = "c3d7e259-decc-4d2e-9349-dab1d3ee3343"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "equiplocate-media" # REPLACE THIS with your actual R2 bucket name